# Generated by Django 2.2.10 on 2020-08-23 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=1)),
                ('groupid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('email', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=13)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgroups.MyGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgroups.MyUser')),
            ],
            options={
                'ordering': ['content', 'createdon'],
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgroups.MyGroup')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgroups.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='mygroup',
            name='users',
            field=models.ManyToManyField(to='sgroups.MyUser'),
        ),
    ]
