# Generated by Django 2.2.10 on 2020-08-24 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgroups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
