# Generated by Django 2.2.10 on 2020-08-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=13, unique=True)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('postid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgroups.User')),
            ],
            options={
                'ordering': ['content', 'createdon'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=1)),
                ('groupid', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.ManyToManyField(to='sgroups.User')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
